services:
  - type: web
    name: eaxy-group-backend
    env: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
  - type: static
    name: eaxy-group-frontend
    env: static
    rootDir: frontend
    buildCommand: ""
    staticPublishPath: ./
