services:
  - type: web
    name: eaxy-group
    env: python
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: python backend/app.py
    autoDeploy: true
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
